name: test docker
on:
  push
jobs:
  create-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/test-docker:test2
      - name: push image
        run: docker push ghcr.io/${{ github.repository_owner }}/test-docker:test2
        
